stages:
  -test
image:  maven:4.0.0 -eclipse-temurin-17

cache:
  paths:
    -.m2/repository

  test_api:
    stage: test
    script:
      - echo "Iniciando testes DESAFIO- SICREDI"
      - mvn clean test -Dmaven.repo.local=.m2/repository
    artifacts:
      when: always
      paths:
        - target/surefire-reports/
      reports:
        junit:
          - target/surefire-reports/TEST-*.xml